# -*- coding: utf-8 -*-
"""lab 1-7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p8vkIkgxi34d1IdMoz3OeZpBR9ywm47t
"""

import time
import random
def selectionSort(list):

  for i in range(len(list)):
    min_idx = i
    for j in range(i+1, len(list)):
      if list[min_idx] > list[j]:
        min_idx = j

    list[i], list[min_idx] = list[min_idx], list[i]

list1 = [i for i in range(1,10000)]
random.shuffle(list1)
print("Original list =%s" % list1)
a = time.time()
selectionSort(list1)
b = time.time()
record = b-a
print("Sorted list by Selection method")
print(list1)
print(record,"초")

def bubbleSort(list):
  n = len(list)

  for i in range(n):
    for j in range(0, n-i-1):
      if list[j] > list[j+1]:
        list[j], list[j+1] = list[j+1], list [j]

list2 = [i for i in range(1,10000)]
random.shuffle(list2)
print("Original list=%s" % list2)
a = time.time()
bubbleSort(list2)
b = time.time()
record = b-a
print("Sorted list by bubble method")
print(list2)
print(record,"초")

def insertionSort(list):
  for i in range(1,len(list)):
    key = list[i]

    j = i-1

    while j >= 0 and key < list[j]:
      list[j+1] = list[j]
      j-=1
    list[j+1] = key

list3 = [i for i in range(10000)]
random.shuffle(list3)
print("Original list = %s" % list3)
a = time.time()
insertionSort(list3)
b = time.time()
record = b-a
print("Sorted list by Insertion method")
print(list3)
print(record,"초")

def sort():
  list.sort()

list4 = [i for i in range(10000)]
random.shuffle(list4)
print("Original list=%s" % list4)
a = time.time()
bubbleSort(list4)
b = time.time()
record = b-a
print("Sorted list by sort function")
print(list4)
print(record,"초")